name: Deploy to Self-Hosted Server

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main
      - text-agent-api
      - caddy-to-nginx-switch
      - gemini-branch

jobs:
  deploy:
    name: Build and Deploy
    # Use the self-hosted runner
    runs-on: self-hosted

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Build Docker images
      - name: Build Docker images
        working-directory: ./text_agent
        run: |
          echo "Building Docker images..."
          docker compose build

      # Deploy all services with Docker Compose
      - name: Deploy with Docker Compose
        working-directory: ./text_agent
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          echo "Deploying all services (including dashboard)..."
          docker compose up -d --remove-orphans

      # Print status of containers
      - name: Container Status
        working-directory: ./text_agent
        run: |
          echo "Checking container status..."
          docker compose ps
