name: Deploy to Self-Hosted Server

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    # Use the self-hosted runner
    runs-on: self-hosted

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Build Docker images
      - name: Build Docker images
        working-directory: ./text_agent
        run: |
          echo "Building Docker images..."
          docker compose build
      # Build dashboard Docker image
      - name: Build dashboard Docker image
        working-directory: ./dashboard
        run: |
          echo "Building dashboard Docker image..."
          docker build -t dashboard:latest .

      # Deploy with Docker Compose
      - name: Deploy with Docker Compose
        working-directory: ./text_agent
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          echo "Deploying application..."
          docker compose up -d --remove-orphans
      # Run dashboard container
      - name: Run dashboard container
        run: |
          echo "Running dashboard container..."
          docker run -d --name dashboard --restart unless-stopped -p 80:80 dashboard:latest

      # Print status of containers
      - name: Container Status
        working-directory: ./text_agent
        run: |
          echo "Checking container status..."
          docker compose ps
      - name: Dashboard Container Status
        run: |
          echo "Checking dashboard container status..."
          docker ps -a | grep dashboard
